#!/bin/sh

# Generate file list for automation subdir
rm -f automation/Makefile.am
cat > automation/Makefile.am <<EOF
## This file is automatically generated.
## Please edit autogen.sh if you need to modify this file.

automationdir = $(datarootdir)/aegisub/automation
automation_DATA = \\
EOF

find automation/ -name '*.lua' -or -name '*.rb' -or -name '*.auto3' -or -name '*.txt' | sed '{s/^automation\//\t/; s/$/ \\/}' >> automation/Makefile.am
echo -e "\tdemos/raytracer-test1.ass \\" >> automation/Makefile.am
echo -e "\tv4-docs/template-scripting-ideas.ass\n\n" >> automation/Makefile.am

autoreconf -f -i -s

