#ifdef _WIN32

// Windows specific settings
#include "config/config_windows.h"

#else

// Generated by configure.in
#include "../acconf.h"

// Unix specific settings and defines.
#include "config/config_unix.h"

#endif // __WINDOWS__
