SRC += \
	command/app.cpp \
	command/audio.cpp \
	command/automation.cpp \
	command/edit.cpp \
	command/grid.cpp \
	command/help.cpp \
	command/keyframe.cpp \
	command/recent.cpp \
	command/subtitle.cpp \
	command/time.cpp \
	command/timecode.cpp \
	command/tool.cpp \
	command/video.cpp \
	command/vis_tool.cpp

SRC += \
	command/command.cpp

HEADER += *.h
