#! /usr/bin/env python
# encoding: utf-8
#
# Copyright (c) 2009, Kevin Ollivier <kollivier@aegisub.org>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

import os

dir = os.path.abspath('.')

def build(bld):
    bld.new_task_gen(
        rule = dir + '/build/default/tools/common-respack ${TGT} ${SRC}',
        source = "default_mru.json",
        target = 'default_config.cpp',
        name = 'default_config',
        after = 'common-respack',
        )

    bld.new_task_gen(
        rule = dir + '/build/default/tools/common-respack ${TGT} ${SRC} ../src/bitmaps/16 ../src/bitmaps/24',
        source = '../bitmaps/misc/splash.png ../bitmaps/misc/wxicon.png',
        target = 'bitmap.cpp',
        after = 'common-respack',
        name = 'bitmap',
        )

    bld.add_group()
    
    bld.new_task_gen(
        features = 'cc cxx cstaticlib',
        target = 'libresrc',
        source = 'bitmap.cpp default_config.cpp libresrc.cpp',
        includes = '.',
        uselib = 'WX',
        after = 'bitmap default_config',
      )
