#if !defined(AGI_PRE) && !defined(LAGI_PRE)

#ifdef _WIN32 // Windows specific settings
#define HAVE_PTHREAD 1
#else

// Generated by configure.in
#include "../acconf.h"

#endif // _WIN32
#endif // LAGI_PRE
