{1}{1}29.970030
{2710}{2779}The year is 2015 A.D.
{3450}{3567}As of 12:30 PM today, a special state|of emergency has been declared
{3571}{3694}for the Kanto and Chubu regions|surrounding the Tokai district.
{3710}{3830}All residents must evacuate to their|designated shelters immediately.
{3844}{3945}Repeating: As of 12:30 PM today,
{3946}{3972}All Lines Stopped|Repeating: As of 12:30 PM today,
{3973}{4018}the Kanto and Chubu regions|surrounding the Tokai district|All Lines Stopped
{4019}{4081}the Kanto and Chubu regions|surrounding the Tokai district
{4084}{4175}have been declared to be under|a state of emergency.
{4178}{4223}All residents must evacuate...
{4224}{4327}Why did I have to lose sight of him now?
{4328}{4378}Oh, man!
{4379}{4382}Ikari Shinji|Oh, man!
{4383}{4413}Ikari Shinji
{4414}{4458}Due to the special emergency,|Ikari Shinji
{4459}{4494}Due to the special emergency,
{4497}{4594}all lines are currently unavailable.
{4638}{4667}It's no use.
{4699}{4767}I shouldn't have come here after all.
{4881}{4896}for me.♥|Attention here!!|I'll be coming to|get you, so wait|To Shinji-kun
{4897}{4952}Well, I guess we won't be meeting here.|for me.♥|Attention here!!|I'll be coming to|get you, so wait|To Shinji-kun
{4953}{4967}Well, I guess we won't be meeting here.
{5002}{5079}Can't be helped. I'll go to a shelter.
{5834}{5848}ESTIMATED PATH
{5849}{5950}The unidentified mobile object is still|advancing on our position.|ESTIMATED PATH
{5951}{5952}The unidentified mobile object is still|advancing on our position.
{5976}{6072}We've got visual confirmation.|I'm putting it on the main screen.
{6123}{6177}It's been fifteen years, hasn't it?
{6180}{6243}Yes, there's no doubt.
{6273}{6309}It's an Angel.
{6310}{6389}Episode One|Angel Attack
{6669}{6723}Every missile hit the target!
{7299}{7346}I'm sorry! Thanks for waiting!
{7856}{7993}The target is still operational.|It's still heading towards New Tokyo-3.
{7996}{8071}The Air Defense Force doesn't have|the firepower to stop it!
{8096}{8130}Hit it with everything we've got!
{8131}{8189}Mobilize all of Atsugi and Iruma as well!
{8192}{8293}Don't hold anything back!|Destroy the target at any cost!
{8693}{8756}Why?! That was a direct hit!
{8771}{8842}The tank battalion's been annihilated.
{8843}{8930}Guided missiles and artillery|have no effect either.
{8931}{9036}It's no good! We'll never get anywhere|with the firepower we've got!
{9037}{9092}AT field: absolute terror field|Is it an AT field after all?
{9093}{9126}Yes. Conventional weapons are|useless against Angels.|AT field: absolute terror field
{9127}{9210}Yes. Conventional weapons are|useless against Angels.
{9314}{9410}I understand. We'll activate it as planned.
{9555}{9599}Hey, don't tell me...
{9602}{9657}They're going to use an N² mine?!
{9673}{9703}Get down!
{10387}{10412}We did it!
{10454}{10546}Sorry, but it looks like you won't be|getting a shot at it.
{10549}{10614}Shock wave approaching.
{10651}{10690}Are you all right?
{10693}{10792}Yeah, but my mouth is full of dirt.
{10793}{10911}That's okay. Now then, here we go!
{10932}{10971}One, two!
{11086}{11132}There.
{11233}{11295}Thanks for the hand. I really appreciate it.
{11298}{11387}Thank you too, Katsuragi-san.
{11390}{11451}Just Misato is fine.
{11466}{11565}I'm glad we've met at last, Ikari Shinji-kun.
{11575}{11599}Yeah...
{11616}{11653}What's the target's status?
{11656}{11742}We're unable to confirm due to|all the EMP interference.
{11745}{11827}You saw the size of the explosion. It's over.
{11830}{11872}Sensors restored.
{11912}{11966}We've got an energy reading|at the explosion's epicenter!
{11969}{12002}What the hell?!
{12005}{12053}Visual display restored.
{12182}{12248}That was our last resort.
{12277}{12333}How can this be?
{12334}{12382}Damned monster!
{12681}{12752}Yes. Don't worry about it.
{12755}{12876}His safety is my top priority,|so could you get a car train ready for us?
{12879}{12915}A direct one.
{12942}{12970}Right.
{12982}{13051}Well, I volunteered to pick him up,
{13052}{13132}so I'll make sure he gets there. See ya!
{13203}{13395}Man, this sucks! I just had my car restored|and it's a total wreck already!
{13410}{13503}33 more loan payments to go,|plus the cost of repairs.
{13506}{13575}And look! My best dress has been ruined!
{13576}{13581}Excuse me, Misato-san?|And look! My best dress has been ruined!
{13582}{13592}Excuse me, Misato-san?
{13593}{13630}And I was looking and feeling so nice.|Excuse me, Misato-san?
{13631}{13705}And I was looking and feeling so nice.
{13706}{13755}Excuse me, Misato-san?
{13762}{13805}What?
{13809}{13888}Are you sure you can just take those?
{13944}{13972}Never mind about that!
{13975}{14087}It's an emergency, and we need|a working car right now, right?
{14090}{14194}And I'm an international government|official, after all,
{14197}{14244}so everything's going to be|perfectly fine, okay?
{14286}{14364}I don't think anyone will buy that.
{14367}{14489}You're no fun. You look cute,|but you're kind of a cold fish.
{14518}{14557}You think so?
{14560}{14611}Oh, did I upset you?
{14634}{14735}Sorry about that! You are a boy, after all.
{14738}{14836}And you're pretty childish for your age.
{15008}{15095}As we predicted, it's regenerating itself.
{15105}{15220}If it couldn't, it wouldn't be|a practical autonomous weapon.
{15330}{15437}Impressive. It appears it can even upgrade|its own operational functions.
{15448}{15515}And it seems to have gotten smarter.
{15547}{15633}It's only a matter of time before|it resumes attacking.
{15676}{15773}The gates are now closing.|Please stand clear.
{15774}{15782}The special duty organization Nerv?|The gates are now closing.|Please stand clear.
{15783}{15825}Now departing.|The special duty organization Nerv?
{15826}{15828}Now departing.
{15829}{15834}Yes, it's a secret organization under|the control of the United Nations.|Now departing.
{15835}{15927}This is the C-22 Special Express|departing directly for G33-1.|Yes, it's a secret organization under|the control of the United Nations.
{15928}{15942}This is the C-22 Special Express|departing directly for G33-1.
{15943}{15991}That's where my father is, right?|This is the C-22 Special Express|departing directly for G33-1.
{15992}{16026}Well, yeah.|This is the C-22 Special Express|departing directly for G33-1.
{16027}{16086}Do you know what he does?|This is the C-22 Special Express|departing directly for G33-1.
{16127}{16204}This train will bypass all other stations.|Please stand back.
{16205}{16241}My teacher told me his work is vital|for the protection of the human race.|This train will bypass all other stations.|Please stand back.
{16242}{16319}My teacher told me his work is vital|for the protection of the human race.
{16414}{16508}From this point forward, command of this|operation will be entrusted to you.
{16511}{16559}Show us what you're capable of.
{16562}{16594}Yes, Sir.
{16612}{16794}Ikari-kun, we will admit that our weapons|have no effect on the target.
{16822}{16893}But are you sure you can beat this thing?
{16908}{16957}It's what Nerv was created for.
{16983}{17027}Let's hope you're correct.
{17077}{17140}The target is still stationary.
{17143}{17243}Our intercept system is currently|7.5% operational.
{17294}{17363}So, even the UN forces have retired.
{17366}{17413}What are you going to do?
{17429}{17488}I intend to activate Unit 01.
{17496}{17588}Unit 01? But we have no pilot.
{17608}{17715}That's not a problem. Another spare|will be delivered soon.
{17745}{17826}Are you taking me to my father?
{17842}{17904}Yes. Pretty much.
{18020}{18057}Father...
{18105}{18205}Oh, that's right. Did you get|an ID card from your father?
{18263}{18292}Yes.
{18343}{18373}Here it is.
{18376}{18398}Thanks.
{18399}{18414}Ikari Gendo|Come.|Thanks.
{18415}{18434}Come.|Ikari Gendo
{18456}{18524}Then read this.
{18525}{18527}Nerv|Welcome to|Then read this.
{18528}{18549}Welcome to|Nerv
{18550}{18574}Nerv...|Welcome to|Nerv
{18575}{18585}Nerv...
{18612}{18649}My father's agency.
{18672}{18733}Am I going to work for them too?
{18792}{18836}Of course.
{18842}{18965}He wouldn't have sent me a letter unless|he needed me for something.
{18980}{19068}I see. So you don't get along with your father.
{19111}{19158}It's the same with me.
{19338}{19375}Awesome!
{19412}{19462}It's the real Geo-Front!
{19465}{19491}That's right.
{19494}{19596}This is our secret base.|Nerv Headquarters.
{19609}{19654}This is the key to rebuilding our world.
{19657}{19730}A fortress for all mankind.
{19928}{19993}That's strange. Isn't this the right way?
{19994}{20037}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20038}{20039}Central Dogma|Nerv Headquarters|Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20040}{20040}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20041}{20041}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20042}{20043}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20044}{20044}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20045}{20045}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20046}{20046}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20047}{20047}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20048}{20049}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20050}{20050}Around here|Central Dogma|Nerv Headquarters|That's strange. Isn't this the right way?
{20051}{20051}Around here|Nerv Headquarters|That's strange. Isn't this the right way?
{20052}{20085}That's strange. Isn't this the right way?
{20107}{20154}Central Dogma's closed passages|remain sealed.
{20155}{20167}This is why I hate wearing skirts here.
{20168}{20238}Opening block B-26 in sequence.|This is why I hate wearing skirts here.
{20239}{20253}Opening block B-26 in sequence.
{20254}{20312}But where the heck did Ritsuko go?|Opening block B-26 in sequence.
{20313}{20336}But where the heck did Ritsuko go?
{20339}{20422}I'm sorry. I'm just not used to this place yet.
{20425}{20484}We passed this spot just a little while ago.
{20526}{20568}But don't worry about it.
{20571}{20656}They make these systems|to be used, you know.
{20657}{20738}Would the head of Project E,|Technical Department Division 1,
{20739}{20824}Dr. Akagi Ritsuko, Dr. Akagi Ritsuko,
{20825}{20963}please contact Captain Katsuragi Misato|of Operations, Division 1, immediately.
{20968}{21022}I don't believe it.
{21023}{21051}She got lost again, didn't she?
{21186}{21247}Uh, hiya, Ritsuko.
{21388}{21458}What were you doing, Captain Katsuragi?
{21462}{21528}We're short on both time|and manpower, you know.
{21544}{21574}Sorry!
{21673}{21727}So this is the boy?
{21730}{21847}Right. According to the Marduk report,|he's the "Third Child".
{21869}{21901}I'm glad to meet you.
{21904}{21958}Huh? Sure.
{21969}{22114}He's just like his father.|Like how he's unendearing.
{22126}{22163}I'll leave the rest to you.
{22297}{22363}Their first meeting in over three years.
{22395}{22504}Vice Commander, the target|has started moving again.
{22507}{22608}Right. All personnel, assume|battle stations, Level One.
{22614}{22714}Repeat. All personnel, assume|battle stations, Level One.
{22715}{22756}Prepare for ground-unit interception.
{22772}{22808}Here we go.
{22809}{22845}It sounds pretty serious.
{22880}{22944}So, how's Unit 01 doing?
{22945}{23015}It's currently in refrigeration,|using the B-type equipment.
{23016}{23135}Does it really work?|It's never worked before, right?
{23136}{23283}The possibility of activation is 0.000000001%.
{23302}{23376}We call it, pathetically enough,|the O-9 System.
{23377}{23456}Does that mean it doesn't work?
{23457}{23530}Oh, don't be insulting. It's not zero.
{23531}{23581}Well, it's just a number.
{23584}{23719}Anyway, it's a bit too late to be saying,|"Sorry, it didn't work".
{23978}{24060}Huh? It's completely dark.
{24168}{24250}A face? A giant robot?
{24302}{24366}You won't find this in the manual.
{24401}{24519}This is mankind's ultimate|multipurpose decisive weapon,
{24520}{24636}the synthetic human Evangelion, Unit 01.
{24637}{24793}Built in absolute secrecy,|it is mankind's trump card.
{24794}{24853}Is this part of what my father's been doing?
{24854}{24880}Correct.
{24940}{24979}It's been a while.
{25012}{25045}Father...
{25138}{25160}We're moving out!
{25176}{25279}Moving out?! Unit 00's still in|cryo-stasis, isn't it?
{25338}{25403}You're not planning to use Unit 01?!
{25428}{25473}There's no other way.
{25474}{25559}Hold on! Rei can't do it yet, can she?
{25588}{25629}We've got no pilot!
{25658}{25692}A pilot has just been delivered.
{25731}{25761}Are you serious?
{25791}{25822}Ikari Shinji-kun...
{25823}{25855}Yes?
{25856}{25886}You will pilot it.
{25908}{26057}But even Ayanami Rei took seven months|to synchronize with her Eva.
{26063}{26141}It's impossible for him to do it!|He just got here!
{26144}{26227}He just has to sit in the seat.|We don't expect more than that.
{26230}{26259}But...
{26262}{26341}Repelling that Angel is our ultimate priority.
{26357}{26464}To do that, we have no choice but to put|aboard the Eva whomever has the chance
{26467}{26542}to synchronize with it, no matter how slight.
{26580}{26637}I believe you know that, Captain Katsuragi.
{26712}{26751}I suppose...
{26800}{26871}Father, why did you send for me?
{26872}{26935}You know exactly why.
{26936}{27052}So, you're asking me to take this thing|and fight that thing?
{27074}{27103}That's right.
{27104}{27213}No way! Why are you doing this now?!
{27214}{27291}I thought you didn't need me!
{27292}{27357}I called you because I have a need for you.
{27435}{27477}Why me?
{27497}{27563}Because no one else can.
{27584}{27634}No, I can't...
{27648}{27753}I've never even seen anything|like this before! I can't do this!
{27783}{27824}You will be instructed.
{27844}{27958}But there's no way I can do this!
{27984}{28044}I can't pilot it!
{28089}{28179}If you're going to pilot it, do it now|and quickly. If not, leave!
{28530}{28605}It must have detected our location.
{28715}{28772}Shinji-kun, we don't have time.
{28924}{28958}Get into it.
{28991}{29130}No! I didn't come for this! This isn't fair!
{29169}{29271}Shinji-kun, just why did you come here?
{29329}{29451}You mustn't run! Not from your father,|and most of all not from yourself.
{29471}{29592}I know that! But there's no way I can do it!
{29837}{29866}Fuyutsuki...
{29906}{29947}Wake up Rei.
{29948}{29992}Can we use her?
{29993}{30039}She isn't dead.
{30074}{30107}I understand.
{30162}{30187}Rei.
{30188}{30221}Yes?
{30222}{30307}Our spare is unusable. You will do it again.
{30308}{30336}Yes, Sir.
{30405}{30507}Reconfigure Unit 01's system to Rei,|then re-activate!
{30508}{30599}Roger. Call off the present work,|and begin re-activation.
{30659}{30773}I knew it. I'm not needed after all.
{31789}{31819}Watch out!
{32108}{32154}The Eva moved!
{32155}{32190}What's going on?!
{32191}{32261}It broke the right arm restraint!
{32262}{32308}No, that's impossible!
{32324}{32389}It didn't even have an entry plug inserted!
{32390}{32426}There's no way it could have moved!
{32461}{32527}It reacted without any interface?!
{32552}{32613}Or was it protecting...
{32614}{32644}him?
{32684}{32713}We can do it.
{33344}{33481}I mustn't run away. I mustn't run away.|I mustn't run away. I mustn't run away.
{33482}{33516}I mustn't run away!
{33560}{33586}I'll do it.
{33608}{33641}I'll pilot it!
{33748}{33786}Cooling process, completed.
{33787}{33832}Right arm re-secured.
{33833}{33893}Cage contents now in position for docking.
{33894}{33921}Roger.
{33922}{34006}Signal terminator plug has been ejected.
{34023}{34100}Roger. Inserting entry plug.
{34101}{34192}Direct hydro-transmission system,|connection prepared.
{34314}{34358}Plug fixed in place.
{34359}{34410}First stage connection initiated.
{34558}{34612}Filling the entry plug.
{34648}{34689}What is this stuff?
{34808}{34898}Don't worry. Once your lungs|are filled with LCL,
{34899}{34981}your blood will be oxygenated directly.
{34982}{35021}You'll get used to it.
{35126}{35168}I feel nauseous.
{35169}{35236}Stop whining! You're a boy, aren't you?!
{35276}{35309}Connecting main power.
{35310}{35390}All circuits transmitting power.
{35391}{35415}Roger.
{35416}{35465}Commencing secondary contacts.
{35513}{35585}A-10 nerve connection, normal.
{35586}{35741}Set the thought configuration to Japanese.
{35768}{35840}All preliminary contacts established.|Performance nominal.
{35841}{35894}Bi-directional circuits are open.
{35911}{35986}Synchronization rate at 41.3%.
{36006}{36042}Amazing.
{36043}{36150}Harmonics are all normal.|No disturbances identified.
{36174}{36204}We can do it.
{36246}{36282}Prepare to launch!
{36342}{36387}Prepare to launch!
{36388}{36431}Disengage primary lock bolts!
{36478}{36572}Disengage confirmed.|Disengaging the umbilical bridge.
{36645}{36686}Disengage secondary lock bolts.
{36757}{36814}Disengage primary restraints.
{36815}{36887}Likewise, disengage secondary restraints.
{36992}{37079}Release safety locks numbers|one through fifteen.
{37080}{37110}Release confirmed.
{37123}{37186}Currently, Unit 01's condition is free.
{37187}{37235}Internal batteries fully charged.
{37236}{37296}External battery outlet, normal.
{37314}{37401}Roger. Move Eva Unit 01|to the ejector pad.
{37869}{37925}Launch path is clear. All systems green.
{37938}{37977}Ready for launch.
{38010}{38037}Roger.
{38063}{38095}Can we really do this?
{38096}{38127}Of course.
{38154}{38230}Unless we defeat the Angels,|we have no future.
{38278}{38367}Ikari, you're really sure about this?
{38417}{38445}Launch!
{39464}{39525}Shinji-kun, don't get killed out there.
{39526}{39526}To Be Continued|Shinji-kun, don't get killed out there.
{39527}{39574}To Be Continued
{41535}{41561}Preview
{41562}{41602}Eva triumphs over the Angel!
{41603}{41670}However, that was just the beginning.
{41678}{41726}Shinji runs away from his father.
{41727}{41828}Misato's arrogance leads her|to try to save him.
{41840}{41910}Next Evangelion: "Unfamiliar Ceiling"
{41911}{41922}I'll give you fan service next time too!
{41923}{41971}Next Episode|Unfamiliar Ceiling|I'll give you fan service next time too!
{41972}{41984}Unfamiliar Ceiling|Next Episode
