# Use Homebrew build tools, but exclude its target libraries from discovery.
[properties]
pkg_config_libdir = ['/usr/lib/pkgconfig']

[built-in options]
pkg_config_path = []

[cmake]
CMAKE_IGNORE_PREFIX_PATH = ['/opt/homebrew', '/usr/local']
